name: Build and upload Latex documents

on:
  push:
    branches:
      - master
      - dev
    paths:
      - src/**/*
  workflow_dispatch:
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Add version to filenames
        run: |
          shopt -s extglob

          VERSION_LOG_PATH="sezioni/registro_mod.tex"

          for doc in src/*(Interni|Esterni)/!(Verbali)/*.tex; do
              path="$(dirname $doc)"
              log_path="${path}/${VERSION_LOG_PATH}"
              if [ -f "$log_path" ]; then
                  version="$(cat $log_path | grep -E -m 1 -o '^[0-9]+\.[0-9]+\.[0-9]+' | sed 's#\.#_#g')"
                  versioned_doc="${doc//".tex"/"_v${version}.tex"}"
                  mv "$doc" "$versioned_doc"
              fi
          done
      
      - name: Compile documents
        uses: xu-cheng/latex-action@v2
        with:
          root_file: |
            src/Esterni/**/*.tex
            src/Interni/**/*.tex
            src/!(common|classes|assets)/*.tex
          glob_root_file: true
          work_in_root_file_dir: true

      - name: Copy to build directory
        run: |
          mkdir build
          rsync -am --include "*.pdf"  --include "*/" --exclude "*"  src/ build/

      - name: Upload as artifacts
        uses: actions/upload-artifact@v3
        with:
          name: documents
          path: build/
          retention-days: 7
      
      - name: Upload to GDrive with rclone
        uses: wei/rclone@v1
        env:
          RCLONE_CONFIG_SHARED_TYPE: drive
          RCLONE_CONFIG_SHARED_CLIENT_ID: ${{ secrets.DRIVE_CLIENT_ID }}
          RCLONE_CONFIG_SHARED_CLIENT_SECRET: ${{ secrets.DRIVE_CLIENT_SECRET }}
          RCLONE_CONFIG_SHARED_SCOPE: drive.file
          RCLONE_CONFIG_SHARED_ROOT_FOLDER_ID: ${{ secrets.DRIVE_ROOT_ID }}
          RCLONE_CONFIG_SHARED_TOKEN: ${{ secrets.DRIVE_TOKEN }}
        with:
          args: 'sync build/ "shared:${GITHUB_REF_NAME}" -P'
