name: Build and upload Latex documents

on:
  push:
    branches:
      - master
    paths:
      - src/**/*
  workflow_dispatch:
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Compile documents
        uses: xu-cheng/latex-action@v2
        with:
          root_file: |
            src/*.tex
            src/!(common|classes|assets)/*.tex
          glob_root_file: true
          work_in_root_file_dir: true
      
      - name: Move to build directory
        run: |
          mkdir -p build/Verbali/Interni build/Verbali/Esterni
          for pdf in $(find src -iname "*.pdf"); do
            filename=$(basename "$pdf")
            if [[ "$filename" == vi_*.pdf ]]; then
              mv "$pdf" build/Verbali/Interni
            elif [[ "$filename" == ve_*.pdf ]]; then
              mv "$pdf" build/Verbali/Esterni
            else
              mv "$pdf" build/
            fi
          done

      - name: Upload to GDrive with rclone
        uses: wei/rclone@v1
        env:
          RCLONE_CONF: ${{ secrets.RCLONE_CONF }}
        with:
          args: sync build/ bb-shared:master -P

      - name: Upload as artifacts
        uses: actions/upload-artifact@v3
        with:
          name: documents
          path: build/
          retention-days: 7
